[[section-introduction-and-goals]]
== Introducción y objetivos

[role="arc42help"]
****
Describe los requisitos relevantes y las fuerzas impulsoras que los arquitectos de software y el equipo de desarrollo deben considerar. Éstas incluyen

* objetivos comerciales subyacentes, características esenciales y requisitos funcionales para el sistema
* objetivos de calidad para la arquitectura
* partes interesadas relevantes y sus expectativas
****

=== Descripción general de los requisitos

[role="arc42help"]
****
.Contenidos
Breve descripción de los requisitos funcionales, fuerzas motrices, extracto (o resumen)
de requisitos Enlace a documentos de requisitos (con suerte existentes)
(con número de versión e información donde encontrarlo).

.Motivación
Desde el punto de vista de los usuarios finales, se crea o modifica un sistema para
mejorar el apoyo de una actividad empresarial y/o mejorar la calidad.

.Formulario
Breve descripción textual, probablemente en formato de caso de uso tabular.
Si existen documentos de requisitos, este resumen debe hacer referencia a estos documentos.

Mantenga estos extractos lo más cortos posible. Equilibre la legibilidad de este documento con la posible redundancia en relación con los documentos de requisitos.
****

=== Objetivos de calidad

[role="arc42help"]
****
.Contenido
Los tres (máximo cinco) objetivos de calidad para la arquitectura cuyo cumplimiento es de suma importancia para las principales partes interesadas. Realmente nos referimos a objetivos de calidad para la arquitectura. No los confunda con los objetivos del proyecto. No son necesariamente idénticos.

.Motivación
Debe conocer los objetivos de calidad de sus partes interesadas más importantes, ya que influirán en las decisiones arquitectónicas fundamentales. Asegúrese de ser muy concreto acerca de estas cualidades, evite las palabras de moda.
Si usted como arquitecto no sabe cómo se juzgará la calidad de su trabajo…

.Formulario
Una tabla con objetivos de calidad y escenarios concretos, ordenados por prioridades
****

=== Stakeholders

[role="arc42help"]
****
.Contenido
Resumen explícito de las partes interesadas del sistema, es decir, todas las personas, roles u organizaciones que

* debe conocer la arquitectura
* hay que estar convencido de la arquitectura
* tiene que trabajar con la arquitectura o con código
* necesitan la documentación de la arquitectura para su trabajo
* tener que llegar a decisiones sobre el sistema o su desarrollo

.Motivación
Debe conocer a todas las partes involucradas en el desarrollo del sistema o afectadas por el sistema.
De lo contrario, puede recibir sorpresas desagradables más adelante en el proceso de desarrollo.
Estas partes interesadas determinan la extensión y el nivel de detalle de su trabajo y sus resultados.

.Formulario
Tabla con nombres de roles, nombres de personas y sus expectativas con respecto a la arquitectura y su documentación.
****

Añadir tabla aquí :)












[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
