[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

Restricciones tecnicas

- Implementacion	La aplicacion estará formada por un front-end utilizando React  con TypeScript y un back-end utilizando NodeJS con Express
- Seguridad		    Se seguirán los principios SOLID a la hora de almacenar la informacion del login del usuario para poder asegurar la privacidad de este.
- Despliegue		La aplicacion será accesible de manera continua y utilizará un sistema de integracion continuo.

Restriciones organizacionales

- Equipo	                                Alejandro Galán Freire, Aarón García García, Mario Lada Martínez, Jorge López Peláez y Rafael Muñiz Reguera.
- Configuracion y control del repositorio 	Toda la aplicacion se encuentra en un repositorio privado de github donde existe una rama develop general y cada persona
                                            del equipo trabajará desde una rama propia.

Convenciones

- Documentacion de la arquitectura	Estructura basada en la plantilla arc42.
- Convenciones de codificacion      El proyecto utiliza las convenciones de codigo para el lenguaje de TypeScript.
- Idioma				            Español. 