[[section-runtime-view]]
== Vista de tiempo de ejecución


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines


* ...

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----

****

=== Compra de productos
[plantuml,"ComprarProducto",png]
----
actor Usuario #green
database BaseDeDatos as "Base de datos" #blue
database Pod as "Pod del usuario" #yellow
Usuario -> DeDe: Abre el carrito
DeDe <-- BaseDeDatos: Devuelve contenido del carrito del usuario
Usuario <-- DeDe: Muestra lista de juguetes del carrito
Usuario -> DeDe: Presiona botón realizar pedido
DeDe -> Pod: Se solicita la dirección del usuario
Usuario -> Pod: Inicia sesión en Pod y añade su dirección en la sección "notes" del mismo
DeDe <-- Pod: Devuelve la dirección del usuario
DeDe -> DeDe: Muestra la dirección y se calculan gastos de envío (API GeoCode)
Usuario <-- DeDe: Muestra el precio y la dirección.
Usuario -> DeDe: Recorre pantallas de pago hasta confirmar el pedido.
----

=== Añadir productos
[plantuml,"AñadirProducto",png]
----
actor Admin #green
database BaseDeDatos as "Base de datos" #blue
Admin -> Dede: Accede  a la página para iniciar sesión
Admin -> Dede: Rellena la pagina con una cuenta de administrador
Admin <- Dede: La aplicación redirige al usuario a la página principal
Admin -> Dede: Accede a la sección "Añadir producto" y rellena los datos
Dede -> BaseDeDatos: Añade el nuevo producto
BaseDeDatos -> Dede: Devuelve la nueva lista de productos
Dede -> Admin: Muestra todos los productos
----

=== Filtrar productos
[plantuml,"FiltrarProducto",png]
----
actor Usuario #green
Usuario -> Dede: Navega a la sección de juguete y presiona uno de los botones de filtrado por categorías
Dede --> Dede: La aplicación hace un filtrado de todo el listado de los juguetes quedándose solo con la categoría especificada
Usuario <- Dede: Muestra los juguetes encontrados con el filtro
----

=== Iniciar sesión
[plantuml,"InicioSesion",png]
----
actor Usuario #green
database BaseDeDatos as "Base de datos" #blue
Usuario -> Dede: Accede a la página y presiona el botón "Registrarse"
Usuario <- Dede: Se despliega un formulario de inicio de sesión aportado por la API Auth0
Usuario -> Dede: Rellena el formulario
BaseDeDatos <-- Dede: Se almacena el usuario recién registrado como cliente en la base de datos (si no está ya almacenado)
Usuario <- Dede: Se muestra la página principal de la aplicación, con unas opciones u otras en función del rol del usuario (se usa el localStorage)
----

=== Cierre de sesión
[plantuml,"CierreSesión",png]
----
actor Usuario
database BaseDeDatos as "Base de datos" #blue
Usuario -> Dede: Accede a la página y presiona el botón "Registrarse"
Usuario -> Dede: Rellena el formulario de registro/inicio sesión que aporta Auth0
BaseDeDatos <-- Dede: Se almacena el usuario recién registrado como cliente en la base de datos (si no está ya almacenado)
Usuario <- Dede: Se muestra la página principal de la aplicación
Usuario -> Dede: Presiona el botón de "Desconectarse"
Usuario <- Dede: Se muestra la página principal de la aplicación con las funciones de un usuario normal
----