[[section-runtime-view]]
== Vista de tiempo de ejecución


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines


* ...

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----

****

=== Compra de productos
[plantuml,"Sequence diagram",png]
----
actor Usuario
database BaseDeDatos as 'Base de datos' #blue
database Pod as 'Pod del usuario' #yellow
Usuario -> DeDe: Abre el carrito
DeDe <-- BaseDeDatos: Devuelve contenido del carrito del usuario
Usuario <-- DeDe: Muestra lista de juguetes del carrito
Usuario -> DeDe: Confirma la compra de los productos
DeDe -> Pod: Se solicita la dirección del usuario
DeDe <-- Pod: Devuelve la dirección del usuario
DeDe -> DeDe: Crea el pedido con el coste y dirección asociados.
Usuario <-- DeDe: Muestra el precio y la dirección.
Usuario -> DeDe: Confirma el pedido.
----

=== <Diagrama de secuencia 2>

=== ...

=== <Diagrama de secuencia n>

=== ...

=== <Runtime Scenario n>
