[[section-runtime-view]]
== Vista de tiempo de ejecución


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines


* ...

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----

****

=== Compra de productos
[plantuml,"ComprarProducto",png]
----
actor Usuario #green
database BaseDeDatos as "Base de datos" #blue
database Pod as "Pod del usuario" #yellow
database GeoCoder as "GeoCoder" #yellow
Usuario -> DeDe: Abre el carrito
DeDe <-- DeDe: Devuelve contenido del carrito del usuario
Usuario <-- DeDe: Muestra pantalla de pago
Usuario -> DeDe: Presiona botón de obtención de dirección POD
DeDe -> Pod: Se solicita la dirección del usuario
Usuario -> Pod: Inicia sesión en Pod y añade su dirección en la sección "notes" del mismo
DeDe <-- Pod: Devuelve la dirección del usuario
Usuario -> DeDe: Continua con el proceso de compra
DeDe -> GeoCoder: Solicita el calculo de los gastos de envío
DeDe <-- GeoCoder: Se devuelven los gastos de envío.
DeDe -> DeDe: Muestra la dirección y los gastos de envío
Usuario -> DeDe: Continua con la revisión de compra
DeDe -> DeDe: Muestra el resumen del pedido
Usuario -> DeDe: Finaliza el pedido
----

=== Añadir productos
[plantuml,"AñadirProducto",png]
----
actor Admin #green
database BaseDeDatos as "Base de datos" #blue
Admin -> DeDe: Accede  a la página para iniciar sesión
Admin -> DeDe: Rellena la pagina con una cuenta de administrador
Admin <- DeDe: La aplicación redirige al usuario a la página principal
Admin -> DeDe: Accede a la sección "Añadir producto" y rellena los datos
DeDe -> BaseDeDatos: Añade el nuevo producto
DeDe <-- BaseDeDatos: Devuelve la nueva lista de productos
DeDe -> Admin: Muestra todos los productos
----

=== Filtrar productos
[plantuml,"FiltrarProducto",png]
----
actor Usuario #green
Usuario -> DeDe: Navega a la sección de juguete y presiona uno de los botones de filtrado por categorías
DeDe --> DeDe: La aplicación hace un filtrado de todo el listado de los juguetes quedándose solo con la categoría especificada
Usuario <- DeDe: Muestra los juguetes encontrados con el filtro
----

=== Iniciar sesión
[plantuml,"InicioSesion",png]
----
actor Usuario
database BaseDeDatos as "Base de datos" #blue
database Auth0 as "Auth0" #blue
Usuario -> DeDe: Accede  a la página y presiona "Registrarse"
DeDe -> Auth0: Redirecciona al usuario a Auth0
Usuario -> Auth0: Rellena sus datos e inicia sesión con su cuenta
DeDe <-- Auth0: La aplicación redirige al usuario a la página principal
Usuario <- DeDe: Se muestra la página principal de la aplicación, con unas opciones u otras en función del rol del usuario (se usa el localStorage)
----

=== Cierre de sesión
[plantuml,"CierreSesión",png]
----
actor Usuario
database BaseDeDatos as "Base de datos" #blue
database Auth0 as "Auth0" #blue
Usuario -> DeDe: Accede  a la página y presiona "Registrarse"
DeDe -> Auth0: Redirecciona al usuario a Auth0
Usuario -> Auth0: Rellena sus datos e inicia sesión con una cuenta de administrador
DeDe <-- Auth0: La aplicación redirige al usuario a la página principal
DeDe --> BaseDeDatos: Se almacena el usuario recién registrado como cliente en la base de datos (si no está ya almacenado)
Usuario <- DeDe: Se muestra la página principal de la aplicación
Usuario -> DeDe: Presiona el botón de "Desconectarse"
Usuario <- DeDe: Se muestra la página principal de la aplicación con las funciones de un usuario normal
----


=== Editar productos
[plantuml,"EditarProducto",png]
----
actor Admin #green
database BaseDeDatos as "Base de datos" #blue
database Auth0 as "Auth0" #blue
Admin -> DeDe: Accede  a la página para iniciar sesión
DeDe -> Auth0: Redirecciona al usuario a Auth0
Admin -> Auth0: Rellena sus datos e inicia sesión con una cuenta de administrador
DeDe <-- Auth0: La aplicación redirige al usuario a la página principal
Admin -> DeDe: Accede a la sección "Administrar productos"
Admin -> DeDe: Accede a "Editar producto"
DeDe --> DeDe: Muestra el formulario de edición del producto.
Admin -> DeDe: Accede a "Editar producto"
Admin -> DeDe: Rellena los nuevos campos del producto
Admin -> DeDe: Confirma los cambios
DeDe --> BaseDeDatos: Actualiza los cambios realizados en el producto.
----

=== Histórico de pedidos
[plantuml,"HistóricoPedidos",png]
----
actor Usuario
database BaseDeDatos as "Base de datos" #blue
Usuario -> DeDe: Accede a la página y presiona el botón "Registrarse"
Usuario -> DeDe: Rellena el formulario de registro/inicio sesión que aporta Auth0
DeDe --> BaseDeDatos: Se almacena el usuario recién registrado como cliente en la base de datos (si no está ya almacenado)
Usuario <- DeDe: Se muestra la página principal de la aplicación
Usuario -> DeDe: Presiona el botón de "Historial Pedidos"
Usuario <- DeDe: Se muestra una página con un registro de los pedidos del usuario iniciado en sesión
----


