[[section-design-decisions]]
== Decisiones de diseño
Utilizaremos las tecnologías ya mencionadas anteriormente, la pila MERN, ya que por experiencia de muchos desarrolladores son herramientas
que se coordinan muy bien. 
No podemos decir con precisión decisiones de diseño definitivas a estas alturas del desarrollo, pero tenemos pensado
utilizar el Modelo Vista-Controlador para que la aplicación sea fácilmente ampliable en cuanto a funcionalidad. Podría surgir
el uso de otros patrones conocidos como por ejemplo Command o Factory, pero es algo que iremos utilizando conforme vayamos desarrollando la
aplicación. 

[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
